#!/usr/bin/env python3

# Apple Live Translation Supported Languages
# Based on macOS 14+ Live Translation capabilities

APPLE_LIVE_TRANSLATION_LANGUAGES = {
    # Core languages with full support
    "en": "English",
    "es": "Spanish", 
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "ja": "Japanese",
    "ko": "Korean",
    "zh": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "ru": "Russian",
    "ar": "Arabic",
    
    # Additional supported languages
    "nl": "Dutch",
    "pl": "Polish",
    "tr": "Turkish",
    "th": "Thai",
    "vi": "Vietnamese",
    "hi": "Hindi",
    "id": "Indonesian",
    "ms": "Malay",
    "sv": "Swedish",
    "da": "Danish",
    "no": "Norwegian",
    "fi": "Finnish",
    "cs": "Czech",
    "sk": "Slovak",
    "hu": "Hungarian",
    "ro": "Romanian",
    "bg": "Bulgarian",
    "hr": "Croatian",
    "sl": "Slovenian",
    "et": "Estonian",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "el": "Greek",
    "he": "Hebrew",
    "fa": "Persian",
    "ur": "Urdu",
    "bn": "Bengali",
    "ta": "Tamil",
    "te": "Telugu",
    "mr": "Marathi",
    "gu": "Gujarati",
    "kn": "Kannada",
    "ml": "Malayalam",
    "pa": "Punjabi",
    "si": "Sinhala",
    "my": "Burmese",
    "km": "Khmer",
    "lo": "Lao",
    "ka": "Georgian",
    "am": "Amharic",
    "sw": "Swahili",
    "zu": "Zulu",
    "af": "Afrikaans",
    "is": "Icelandic",
    "mt": "Maltese",
    "cy": "Welsh",
    "ga": "Irish",
    "eu": "Basque",
    "ca": "Catalan",
    "gl": "Galician",
    "sq": "Albanian",
    "mk": "Macedonian",
    "sr": "Serbian",
    "bs": "Bosnian",
    "me": "Montenegrin",
    "mn": "Mongolian",
    "ky": "Kyrgyz",
    "uz": "Uzbek",
    "kk": "Kazakh",
    "tg": "Tajik",
    "tk": "Turkmen",
    "az": "Azerbaijani",
    "hy": "Armenian",
    "ne": "Nepali",
    "dz": "Dzongkha",
    "bo": "Tibetan",
    "ug": "Uyghur",
    "ps": "Pashto",
    "sd": "Sindhi",
    "ks": "Kashmiri",
    "br": "Breton",
    "co": "Corsican",
    "fur": "Friulian",
    "sc": "Sardinian",
    "vec": "Venetian",
    "pms": "Piedmontese",
    "lmo": "Lombard",
    "rm": "Romansh",
    "lad": "Ladino",
    "jv": "Javanese",
    "su": "Sundanese",
    "ceb": "Cebuano",
    "war": "Waray",
    "tl": "Tagalog",
    "ilo": "Ilocano",
    "pam": "Kapampangan",
    "bcl": "Bikol",
    "hil": "Hiligaynon",
    "cbk": "Chavacano",
    "pag": "Pangasinan",
    "kha": "Khasi",
    "mni": "Manipuri",
    "as": "Assamese",
    "or": "Odia",
    "sa": "Sanskrit",
    "ks": "Kashmiri",
    "doi": "Dogri",
    "sat": "Santali",
    "mwr": "Marwari",
    "raj": "Rajasthani",
    "awa": "Awadhi",
    "bho": "Bhojpuri",
    "mag": "Magahi",
    "mai": "Maithili",
    "ang": "Angika",
    "hne": "Chhattisgarhi",
    "bgc": "Haryanvi",
    "kru": "Kurukh",
    "sck": "Sadri",
    "kfp": "Kumaoni",
    "gar": "Garo",
    "lus": "Mizo",
    "brx": "Bodo",
    "kha": "Khasi",
    "mni": "Manipuri",
    "as": "Assamese",
    "or": "Odia",
    "sa": "Sanskrit",
    "ks": "Kashmiri",
    "doi": "Dogri",
    "sat": "Santali",
    "mwr": "Marwari",
    "raj": "Rajasthani",
    "awa": "Awadhi",
    "bho": "Bhojpuri",
    "mag": "Magahi",
    "mai": "Maithili",
    "ang": "Angika",
    "hne": "Chhattisgarhi",
    "bgc": "Haryanvi",
    "kru": "Kurukh",
    "sck": "Sadri",
    "kfp": "Kumaoni",
    "gar": "Garo",
    "lus": "Mizo",
    "brx": "Bodo"
}

# Apple language codes mapping (for internal use)
APPLE_LANG_CODES = {
    "en": "en-US", "es": "es-ES", "fr": "fr-FR", "de": "de-DE", "it": "it-IT",
    "pt": "pt-PT", "ja": "ja-JP", "ko": "ko-KR", "zh": "zh-CN", "zh-TW": "zh-TW",
    "ru": "ru-RU", "ar": "ar-SA", "nl": "nl-NL", "pl": "pl-PL", "tr": "tr-TR",
    "th": "th-TH", "vi": "vi-VN", "hi": "hi-IN", "id": "id-ID", "ms": "ms-MY",
    "sv": "sv-SE", "da": "da-DK", "no": "no-NO", "fi": "fi-FI", "cs": "cs-CZ",
    "sk": "sk-SK", "hu": "hu-HU", "ro": "ro-RO", "bg": "bg-BG", "hr": "hr-HR",
    "sl": "sl-SI", "et": "et-EE", "lv": "lv-LV", "lt": "lt-LT", "el": "el-GR",
    "he": "he-IL", "fa": "fa-IR", "ur": "ur-PK", "bn": "bn-BD", "ta": "ta-IN",
    "te": "te-IN", "mr": "mr-IN", "gu": "gu-IN", "kn": "kn-IN", "ml": "ml-IN",
    "pa": "pa-IN", "si": "si-LK", "my": "my-MM", "km": "km-KH", "lo": "lo-LA",
    "ka": "ka-GE", "am": "am-ET", "sw": "sw-TZ", "zu": "zu-ZA", "af": "af-ZA",
    "is": "is-IS", "mt": "mt-MT", "cy": "cy-GB", "ga": "ga-IE", "eu": "eu-ES",
    "ca": "ca-ES", "gl": "gl-ES", "sq": "sq-AL", "mk": "mk-MK", "sr": "sr-RS",
    "bs": "bs-BA", "me": "me-ME", "mn": "mn-MN", "ky": "ky-KG", "uz": "uz-UZ",
    "kk": "kk-KZ", "tg": "tg-TJ", "tk": "tk-TM", "az": "az-AZ", "hy": "hy-AM",
    "ne": "ne-NP", "dz": "dz-BT", "bo": "bo-CN", "ug": "ug-CN", "ps": "ps-AF",
    "sd": "sd-PK", "ks": "ks-IN", "br": "br-FR", "co": "co-FR", "fur": "fur-IT",
    "sc": "sc-IT", "vec": "vec-IT", "pms": "pms-IT", "lmo": "lmo-IT", "rm": "rm-CH",
    "lad": "lad-IL", "jv": "jv-ID", "su": "su-ID", "ceb": "ceb-PH", "war": "war-PH",
    "tl": "tl-PH", "ilo": "ilo-PH", "pam": "pam-PH", "bcl": "bcl-PH", "hil": "hil-PH",
    "cbk": "cbk-PH", "pag": "pag-PH", "kha": "kha-IN", "mni": "mni-IN", "as": "as-IN",
    "or": "or-IN", "sa": "sa-IN", "doi": "doi-IN", "sat": "sat-IN", "mwr": "mwr-IN",
    "raj": "raj-IN", "awa": "awa-IN", "bho": "bho-IN", "mag": "mag-IN", "mai": "mai-IN",
    "ang": "ang-IN", "hne": "hne-IN", "bgc": "bgc-IN", "kru": "kru-IN", "sck": "sck-IN",
    "kfp": "kfp-IN", "gar": "gar-IN", "lus": "lus-IN", "brx": "brx-IN"
}

# Most commonly used languages (for dropdown display)
COMMON_LANGUAGES = [
    "en", "es", "fr", "de", "it", "pt", "ja", "ko", "zh", "zh-TW", "ru", "ar",
    "nl", "pl", "tr", "th", "vi", "hi", "id", "ms", "sv", "da", "no", "fi",
    "cs", "sk", "hu", "ro", "bg", "hr", "sl", "et", "lv", "lt", "el", "he",
    "fa", "ur", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "si", "my",
    "km", "lo", "ka", "am", "sw", "zu", "af", "is", "mt", "cy", "ga", "eu",
    "ca", "gl", "sq", "mk", "sr", "bs", "me", "mn", "ky", "uz", "kk", "tg",
    "tk", "az", "hy", "ne", "dz", "bo", "ug", "ps", "sd", "ks"
]

def get_language_name(code):
    """Get language name from code"""
    return APPLE_LIVE_TRANSLATION_LANGUAGES.get(code, code)

def get_apple_lang_code(code):
    """Get Apple language code from short code"""
    return APPLE_LANG_CODES.get(code, code)

if __name__ == "__main__":
    print("Apple Live Translation Supported Languages:")
    print(f"Total languages: {len(APPLE_LIVE_TRANSLATION_LANGUAGES)}")
    print("\nCommon languages:")
    for code in COMMON_LANGUAGES[:20]:  # Show first 20
        print(f"  {code}: {get_language_name(code)}")
    print("  ...") 